/* Generated by Yosys 0.9 (git sha1 1979e0b) */

(* src = "controlanddata.v:3" *)
module Controller_RTL(set_E, clr_E, set_F, clr_A_F, incr_A, A2, A3, Start, clock, reset_b);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  (* src = "controlanddata.v:5" *)
  input A2;
  (* src = "controlanddata.v:5" *)
  input A3;
  (* src = "controlanddata.v:5" *)
  input Start;
  (* src = "controlanddata.v:5" *)
  input clock;
  (* src = "controlanddata.v:4" *)
  output clr_A_F;
  (* src = "controlanddata.v:4" *)
  output clr_E;
  (* src = "controlanddata.v:4" *)
  output incr_A;
  (* src = "controlanddata.v:5" *)
  input reset_b;
  (* src = "controlanddata.v:4" *)
  output set_E;
  (* src = "controlanddata.v:4" *)
  output set_F;
  (* onehot = 32'd1 *)
  wire [2:0] state;
  sky130_fd_sc_hd__clkinv_1 _05_ (
    .A(Start),
    .Y(_03_)
  );
  sky130_fd_sc_hd__clkinv_1 _06_ (
    .A(A3),
    .Y(_04_)
  );
  sky130_fd_sc_hd__a21o_1 _07_ (
    .A1(state[0]),
    .A2(_03_),
    .B1(set_F),
    .X(_01_)
  );
  sky130_fd_sc_hd__and2_0 _08_ (
    .A(state[0]),
    .B(Start),
    .X(clr_A_F)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _09_ (
    .A(incr_A),
    .SLEEP(A2),
    .X(clr_E)
  );
  sky130_fd_sc_hd__a211o_1 _10_ (
    .A1(incr_A),
    .A2(_04_),
    .B1(clr_A_F),
    .C1(clr_E),
    .X(_02_)
  );
  sky130_fd_sc_hd__and2_0 _11_ (
    .A(incr_A),
    .B(A2),
    .X(set_E)
  );
  sky130_fd_sc_hd__and3_1 _12_ (
    .A(incr_A),
    .B(A3),
    .C(A2),
    .X(_00_)
  );
  sky130_fd_sc_hd__dfstp_2 _13_ (
    .CLK(clock),
    .D(_01_),
    .Q(state[0]),
    .SET_B(reset_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _14_ (
    .CLK(clock),
    .D(_02_),
    .Q(incr_A),
    .RESET_B(reset_b)
  );
  sky130_fd_sc_hd__dfrtp_1 _15_ (
    .CLK(clock),
    .D(_00_),
    .Q(set_F),
    .RESET_B(reset_b)
  );
  assign state[2:1] = { set_F, incr_A };
endmodule

(* src = "controlanddata.v:47" *)
module Datapath_RTL(A, E, F, set_E, clr_E, set_F, clr_A_F, incr_A, clock);
  (* src = "controlanddata.v:52" *)
  wire [3:0] _00_;
  (* src = "controlanddata.v:52" *)
  wire _01_;
  (* src = "controlanddata.v:52" *)
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  (* src = "controlanddata.v:48" *)
  output [3:0] A;
  (* src = "controlanddata.v:49" *)
  output E;
  (* src = "controlanddata.v:49" *)
  output F;
  (* src = "controlanddata.v:50" *)
  input clock;
  (* src = "controlanddata.v:50" *)
  input clr_A_F;
  (* src = "controlanddata.v:50" *)
  input clr_E;
  (* src = "controlanddata.v:50" *)
  input incr_A;
  (* src = "controlanddata.v:50" *)
  input set_E;
  (* src = "controlanddata.v:50" *)
  input set_F;
  sky130_fd_sc_hd__nand2b_1 _12_ (
    .A_N(incr_A),
    .B(clr_A_F),
    .Y(_03_)
  );
  sky130_fd_sc_hd__o21ai_0 _13_ (
    .A1(clr_A_F),
    .A2(incr_A),
    .B1(A[0]),
    .Y(_04_)
  );
  sky130_fd_sc_hd__o21a_1 _14_ (
    .A1(A[0]),
    .A2(incr_A),
    .B1(_04_),
    .X(_00_[0])
  );
  sky130_fd_sc_hd__nand3_1 _15_ (
    .A(A[0]),
    .B(incr_A),
    .C(A[1]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__a22oi_1 _16_ (
    .A1(A[0]),
    .A2(incr_A),
    .B1(A[1]),
    .B2(_03_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _17_ (
    .A(_05_),
    .SLEEP(_06_),
    .X(_00_[1])
  );
  sky130_fd_sc_hd__nand4_1 _18_ (
    .A(A[0]),
    .B(incr_A),
    .C(A[1]),
    .D(A[2]),
    .Y(_07_)
  );
  sky130_fd_sc_hd__nand2_1 _19_ (
    .A(A[2]),
    .B(_03_),
    .Y(_08_)
  );
  sky130_fd_sc_hd__a21boi_0 _20_ (
    .A1(_05_),
    .A2(_08_),
    .B1_N(_07_),
    .Y(_00_[2])
  );
  sky130_fd_sc_hd__nand3_1 _21_ (
    .A(A[3]),
    .B(_03_),
    .C(_07_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__o21ai_0 _22_ (
    .A1(A[3]),
    .A2(_07_),
    .B1(_09_),
    .Y(_00_[3])
  );
  sky130_fd_sc_hd__nor2_1 _23_ (
    .A(set_E),
    .B(E),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor2_1 _24_ (
    .A(clr_E),
    .B(_10_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__nor2_1 _25_ (
    .A(set_F),
    .B(F),
    .Y(_11_)
  );
  sky130_fd_sc_hd__nor2_1 _26_ (
    .A(clr_A_F),
    .B(_11_),
    .Y(_02_)
  );
  (* src = "controlanddata.v:52" *)
  sky130_fd_sc_hd__dfxtp_1 _27_ (
    .CLK(clock),
    .D(_00_[0]),
    .Q(A[0])
  );
  (* src = "controlanddata.v:52" *)
  sky130_fd_sc_hd__dfxtp_1 _28_ (
    .CLK(clock),
    .D(_00_[1]),
    .Q(A[1])
  );
  (* src = "controlanddata.v:52" *)
  sky130_fd_sc_hd__dfxtp_1 _29_ (
    .CLK(clock),
    .D(_00_[2]),
    .Q(A[2])
  );
  (* src = "controlanddata.v:52" *)
  sky130_fd_sc_hd__dfxtp_1 _30_ (
    .CLK(clock),
    .D(_00_[3]),
    .Q(A[3])
  );
  (* src = "controlanddata.v:52" *)
  sky130_fd_sc_hd__dfxtp_1 _31_ (
    .CLK(clock),
    .D(_01_),
    .Q(E)
  );
  (* src = "controlanddata.v:52" *)
  sky130_fd_sc_hd__dfxtp_1 _32_ (
    .CLK(clock),
    .D(_02_),
    .Q(F)
  );
endmodule

(* top =  1  *)
(* src = "top.v:4" *)
module Design_Example_RTL(A, E, F, Start, clock, reset_b);
  (* src = "top.v:7" *)
  output [3:0] A;
  (* src = "top.v:8" *)
  output E;
  (* src = "top.v:8" *)
  output F;
  (* src = "top.v:9" *)
  input Start;
  (* src = "top.v:9" *)
  input clock;
  (* src = "top.v:11" *)
  wire clr_A_F;
  (* src = "top.v:11" *)
  wire clr_E;
  (* src = "top.v:11" *)
  wire incr_A;
  (* src = "top.v:9" *)
  input reset_b;
  (* src = "top.v:11" *)
  wire set_E;
  (* src = "top.v:11" *)
  wire set_F;
  (* module_not_derived = 32'd1 *)
  (* src = "top.v:11" *)
  Controller_RTL M0 (
    .A2(A[2]),
    .A3(A[3]),
    .Start(Start),
    .clock(clock),
    .clr_A_F(clr_A_F),
    .clr_E(clr_E),
    .incr_A(incr_A),
    .reset_b(reset_b),
    .set_E(set_E),
    .set_F(set_F)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "top.v:12" *)
  Datapath_RTL M1 (
    .A(A),
    .E(E),
    .F(F),
    .clock(clock),
    .clr_A_F(clr_A_F),
    .clr_E(clr_E),
    .incr_A(incr_A),
    .set_E(set_E),
    .set_F(set_F)
  );
endmodule
